Resources:
  MessageCountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.messageCountsTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
