Resources:
  ChannelUpdatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.channelUpdatesTableName}
      AttributeDefinitions:
        - AttributeName: channelId
          AttributeType: S
      KeySchema:
        - AttributeName: channelId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
